name:  build-docs

on: [ push, delete, create ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        env:
           MESSAGEDATA: ${{ github.event.head_commit.message }}
           HEADCOMMITDATA: ${{ github.event.head_commit }}
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
         repository: 'Five-great/tinymce-code'
         token: ${{ secrets.BUILD_ACCESS_TOKEN }}
         persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.x
      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build:site
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          commit-message: ${{ env.MESSAGEDATA }}
          FOLDER: dist
          repository-name: 'Five-great/tinymce-plugin.github.io'
