name:  build-docs

on: [ push, delete, create ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        MESSAGEDATA: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
         repository: ${{secrets.TP_BUILD_REPO}}
         token: ${{ secrets.TP_BUILD_ACCESS_TOKEN }}
         persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.x
      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build:site
          npm run build
       - name: Commit files
        run: |
          git config --local user.email "fivecc@qq.com"
          git config --local user.name "five"
          git add .
          git commit -m "${{env.HEADCOMMITDATA}}"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.TP_BUILD_ACCESS_TOKEN }}
          BRANCH: main
          commit-message: ${{ env.MESSAGEDATA }}
          FOLDER: ${{env.TP_FOLDER}}
          repository-name: 'Five-great/tinymce-plugin.github.io'