name:  synchro-repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          folder: .
          repository-name: 'tinymce-plugin/tinymce-plugin-docs'
